#!/bin/bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../lib/logging.sh"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../lib/system.sh"

log_info "loading required kernel modules"

cat >/etc/modules-load.d/docker.conf <<EOF
br_netfilter
overlay
EOF

modprobe br_netfilter 2>/dev/null || log_warn "br_netfilter not available; will load at Docker start"
modprobe overlay 2>/dev/null || log_warn "overlay not available; will load at Docker start"

log_info "applying sysctl tuning"

# Bootstrap baseline at 50- so operator drop-ins (99-) override intentionally.
cp \
  "${SCRIPT_DIR}/../config/sysctl/50-bootstrap.conf" \
  /etc/sysctl.d/50-bootstrap.conf

# Remove pre-rename orphan from older bootstrap runs to avoid double-load.
rm -f /etc/sysctl.d/99-bootstrap.conf

# Compute RAM-derived dirty page caps at bootstrap time so the values track
# instance resize on rerun. dirty_bytes = min(MemTotal * 10%, 512 MiB);
# dirty_background_bytes = dirty_bytes / 4. Absolute-byte form is required:
# setting vm.dirty_ratio implicitly zeroes vm.dirty_bytes (and vice versa),
# and a percent-based cap explodes on large-RAM hosts.
generate_memory_drop_in() {
  local mem_bytes dirty_bytes dirty_bg_bytes cap
  mem_bytes="$(get_mem_total_bytes)"
  cap=$(( 512 * 1024 * 1024 ))
  dirty_bytes=$(( mem_bytes / 10 ))
  if (( dirty_bytes > cap )); then
    dirty_bytes=${cap}
  fi
  dirty_bg_bytes=$(( dirty_bytes / 4 ))

  cat >/etc/sysctl.d/51-bootstrap-memory.conf <<EOF
# Generated by arm64-bootstrap stage 05 from /proc/meminfo at bootstrap time.
# Derivation: dirty_bytes = min(MemTotal * 0.10, 512 MiB); bg = dirty_bytes / 4.
# MemTotal at generation: $(( mem_bytes / 1024 / 1024 )) MiB.
# Regenerated on every rerun — safe to re-run after instance resize.
vm.dirty_bytes = ${dirty_bytes}
vm.dirty_background_bytes = ${dirty_bg_bytes}
EOF

  log_info "memory drop-in: dirty_bytes=$(( dirty_bytes / 1024 / 1024 ))MiB, dirty_background_bytes=$(( dirty_bg_bytes / 1024 / 1024 ))MiB"
}

generate_memory_drop_in

sysctl --system

log_info "sysctl tuning applied"
