#!/bin/bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../lib/logging.sh"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../lib/system.sh"

log_info "configuring journald"

mkdir -p /etc/systemd/journald.conf.d

# SystemMaxUse is computed from the size of the filesystem hosting
# /var/log/journal (always the root volume in this design).
# Formula: min(fs_size * 2%, 1 GiB), floored at 64 MiB so tiny root disks
# still get a usable cap. Regenerated on every rerun.
generate_journald_drop_in() {
  local fs_bytes max_use_bytes cap floor
  fs_bytes="$(get_fs_size_bytes /var/log)"
  cap=$(( 1024 * 1024 * 1024 ))
  floor=$(( 64 * 1024 * 1024 ))
  max_use_bytes=$(( fs_bytes / 50 ))
  if (( max_use_bytes > cap )); then
    max_use_bytes=${cap}
  fi
  if (( max_use_bytes < floor )); then
    max_use_bytes=${floor}
  fi

  cat >/etc/systemd/journald.conf.d/50-bootstrap.conf <<EOF
# Generated by arm64-bootstrap stage 06.
# SystemMaxUse derived from /var/log filesystem size at bootstrap time:
# min(fs_size * 2%, 1 GiB), floored at 64 MiB.
# /var/log FS size at generation: $(( fs_bytes / 1024 / 1024 )) MiB.
[Journal]
Storage=persistent
SystemMaxUse=${max_use_bytes}
SystemKeepFree=1G
SystemMaxFileSize=64M
MaxRetentionSec=7day
Compress=yes
Seal=yes
ForwardToSyslog=no
EOF

  log_info "journald drop-in: SystemMaxUse=$(( max_use_bytes / 1024 / 1024 ))MiB"
}

generate_journald_drop_in

# Remove pre-rename orphan drop-in from older bootstrap runs.
rm -f /etc/systemd/journald.conf.d/bootstrap.conf

systemctl restart systemd-journald

log_info "journald configured"
